// Auth
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// ShoppingCart
export const SET_SHOPPING_CART = 'SET_SHOPPING_CART';
export const PUSH_ITEMS_TO_CART = 'PUSH_ITEMS_TO_CART';
export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
